version: "2"
services:
  pkg_sender:
    build: .
    container_name: pkg_sender
    volumes:
      - ./files:/dev/sda1/ps4/instalate
    ports:
      - 3333:8033
    environment:
      - PORT=8033
      - STATIC_FILES=/opt/apps/pkg_sender/files
      - LOCALIP=192.168.1.108
      - PS4IP=192.168.1.106
    restart: unless-stopped
